import { Action, ActionPanel, Detail, Form, showToast, Toast } from "@raycast/api";
import React, { useState, useEffect } from "react";
import { runPrompt } from "./lib/api";
import { Prompt } from "./types";
import { useAuth } from "./hooks/useAuth";

interface RunPromptViewProps {
  prompt: Prompt;
}

export default function RunPromptView({ prompt }: RunPromptViewProps) {
  const { user, isAuthenticated, isLoading: authLoading } = useAuth();
  const [input, setInput] = useState("");
  const [output, setOutput] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // Show authentication required message if not authenticated
  useEffect(() => {
    if (!authLoading && !isAuthenticated) {
      showToast({
        style: Toast.Style.Failure,
        title: "Authentication Required",
        message: "Please log in first to run prompts",
      });
    }
  }, [authLoading, isAuthenticated]);

  async function handleRun() {
    if (!isAuthenticated) {
      showToast({
        style: Toast.Style.Failure,
        title: "Authentication Required",
        message: "Please log in first to run prompts",
      });
      return;
    }

    if (!input.trim()) {
      showToast({
        style: Toast.Style.Failure,
        title: "Missing Input",
        message: "Please provide input text",
      });
      return;
    }

    setIsLoading(true);

    try {
      const response = await runPrompt({
        prompt_id: prompt.id,
        input: input.trim(),
      });

      setOutput(response.output);

      await showToast({
        style: Toast.Style.Success,
        title: "Prompt Executed",
        message: "Result generated successfully",
      });
    } catch (error) {
      await showToast({
        style: Toast.Style.Failure,
        title: "Failed to Run Prompt",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    } finally {
      setIsLoading(false);
    }
  }

  // Show loading state while checking authentication
  if (authLoading) {
    return (
      <Form isLoading={true}>
        <Form.Description text="Checking authentication..." />
      </Form>
    );
  }

  // Show authentication required message
  if (!isAuthenticated) {
    return (
      <Form
        actions={
          <ActionPanel>
            <Action.OpenInBrowser
              title="Open Login Command"
              url="raycast://extensions/your-name/prompt-board/login"
              icon="🔐"
            />
          </ActionPanel>
        }
      >
        <Form.Description 
          title="Authentication Required" 
          text="Please log in first to run prompts. Use the Login command to authenticate with Google." 
        />
      </Form>
    );
  }

  if (output) {
    const markdown = `# ${prompt.title}

## Input
${input}

---

## Output
${output}

---

*Generated by PromptBoard for ${user?.user_metadata?.full_name || user?.email}*
`;

    return (
      <Detail
        markdown={markdown}
        actions={
          <ActionPanel>
            <Action.CopyToClipboard title="Copy Output" content={output} />
            <Action.CopyToClipboard
              title="Copy Full Result"
              content={markdown}
              shortcut={{ modifiers: ["cmd", "shift"], key: "c" }}
            />
            <Action title="Run Again" onAction={() => setOutput(null)} />
            <Action.OpenInBrowser
              title="View Profile"
              url="raycast://extensions/your-name/prompt-board/user-profile"
              icon="👤"
              shortcut={{ modifiers: ["cmd"], key: "p" }}
            />
          </ActionPanel>
        }
      />
    );
  }

  return (
    <Form
      isLoading={isLoading}
      actions={
        <ActionPanel>
          <Action.SubmitForm title="Run Prompt" onSubmit={handleRun} />
          <Action.OpenInBrowser
            title="View Profile"
            url="raycast://extensions/your-name/prompt-board/user-profile"
            icon="👤"
            shortcut={{ modifiers: ["cmd"], key: "p" }}
          />
        </ActionPanel>
      }
    >
      <Form.Description 
        title="Running as" 
        text={user?.user_metadata?.full_name || user?.email || "Unknown User"} 
      />
      <Form.Separator />
      <Form.Description title="Prompt" text={prompt.title} />
      <Form.Description title="Template" text={prompt.body} />
      <Form.Separator />
      <Form.TextArea
        id="input"
        title="Your Input"
        placeholder="Enter your text here..."
        value={input}
        onChange={setInput}
      />
    </Form>
  );
}
