import { Action, ActionPanel, Detail, Form, showToast, Toast } from "@raycast/api";
import React, { useState } from "react";
import { runPrompt } from "./lib/api";
import { Prompt } from "./types";

interface RunPromptViewProps {
  prompt: Prompt;
}

export default function RunPromptView({ prompt }: RunPromptViewProps) {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  async function handleRun() {
    if (!input.trim()) {
      showToast({
        style: Toast.Style.Failure,
        title: "Missing Input",
        message: "Please provide input text",
      });
      return;
    }

    setIsLoading(true);

    try {
      const response = await runPrompt({
        prompt_id: prompt.id,
        input: input.trim(),
      });

      setOutput(response.output);

      await showToast({
        style: Toast.Style.Success,
        title: "Prompt Executed",
        message: "Result generated successfully",
      });
    } catch (error) {
      await showToast({
        style: Toast.Style.Failure,
        title: "Failed to Run Prompt",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    } finally {
      setIsLoading(false);
    }
  }

  if (output) {
    const markdown = `# ${prompt.title}

## Input
${input}

---

## Output
${output}

---

*Generated by PromptBoard*
`;

    return (
      <Detail
        markdown={markdown}
        actions={
          <ActionPanel>
            <Action.CopyToClipboard title="Copy Output" content={output} />
            <Action.CopyToClipboard
              title="Copy Full Result"
              content={markdown}
              shortcut={{ modifiers: ["cmd", "shift"], key: "c" }}
            />
            <Action title="Run Again" onAction={() => setOutput(null)} />
          </ActionPanel>
        }
      />
    );
  }

  return (
    <Form
      isLoading={isLoading}
      actions={
        <ActionPanel>
          <Action.SubmitForm title="Run Prompt" onSubmit={handleRun} />
        </ActionPanel>
      }
    >
      <Form.Description title="Prompt" text={prompt.title} />
      <Form.Description title="Template" text={prompt.body} />
      <Form.Separator />
      <Form.TextArea
        id="input"
        title="Your Input"
        placeholder="Enter your text here..."
        value={input}
        onChange={setInput}
      />
    </Form>
  );
}
